# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defaults :
  - modulus_default
  - arch:
      - fully_connected
  - scheduler: tf_exponential_lr  #cosine_annealing_warm_restarts  #
  - optimizer: adam  #lbfgs
  - loss: sum #grad_norm  #
  - _self_

arch:
  fully_connected:
    nr_layers: 6
    layer_size: 150

scheduler:
  #cos annealing:
  #T_0: 50
  #T_mult: 2
  
  #tf_exponential_lr:
  decay_rate: 1
  #decay_steps: 4000

training:
  rec_results_freq: 500
  rec_constraint_freq: 500
  max_steps : 5000

loss:
  weights:
    boundary: 1.0
    data_driven: 1.0
    physics: 0.001

optimizer:
  lr: 1e-3

batch_size:
  BC: 3000
  Data: 3000
  Physics: 3000

graph:
  func_arch: true
